language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: PcTmrBGJSKbqdHZTBXF6lziZf3pVXXIfeq89IACy5LgQ7kMHAWTSU+l4HDsW6ZwUaNDZY7Chff2u6KpXMJPmlQZFKhLg0txHRKxH/559f8iF3a/Uf89VM/pIYA/hZYT5ACMVYqeS0zi2uNrC91DNOQ1GqnjhnjSffB9f7TqbnYBYhd3Zo9hxZ7m7GsHPZ9y2Vrxg+qWtTJa7SEoQ5WuZ4grD1ygrdz1O7Qq4F4cXjSJzkB0k0mY1fQK5/WwrvOJBSKFH4XcaPYjwqA6vFS84KVozOAScr+uYX36zxRW21GP6k0J3AQG0BTXc01NaOqO/eUES+hrophPpp1i9uSB0fPEpZ9theXprnh0yHE7KjXx+THfjGDONTtp1RdTgfZZ/R05Br34Lbo2YmO8pXTThoUqWXoZmuC7p0OoOYx7HYWBOtVPWpPS8oBTFuRI5spQv+S+1ESL1EnhQrSIktfIEH5jgXtxcCq9ahGL9JOsTUIk9pgjcq+LS5OuXB45R5cbTTfvCwJKWoMbLQFv0f7Uq/Y4V6EfOi72u0PBeVuy1c3coakxQK7p7q6RovbxnY3ha6EV6/fQahZZDxYITWOFFy252T6Zo5PkWZdCu+/wTjuLDYQW9KzNtrlpUYRvdHXvhsPjDRKQtIsqusz8maLCkWth3mNMtKm9ZuntiwvpNZ4E=
  file: target/gnuob-shop.war
  on:
    tags: true
